version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da API FastAPI
  api:
    build: .
    container_name: fastapi_api
    restart: always
    network_mode: "host"
    volumes:
      - ./app:/app/app
    env_file:
      - .env

  tests:
    build: .
    container_name: fastapi_tests
    network_mode: "host"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    env_file:
      - .env
    command: >
      sh -c "python -m pytest /app/tests -v"
    environment:
      - PYTHONPATH=/app
      - TESTING=1

volumes:
  pg_data: